### ISSUE TITLE
Internal error: get_class(): Argument #1 ($object) must be of type object, int given

### ISSUE THREAD

**Issue by althaus** [phpstan/phpstan-doctrine#205]
Hi,

I've just updated some of my repositories with the `@extends ServiceEntityRepository<MyClass>` annotation and phpstan-doctrine crashes on one with the following stacktrace:

~~~
Uncaught TypeError: get_class(): Argument #1 ($object) must be of type object, int given in /path/to/project/vendor\doctrine\orm\lib\Doctrine\ORM\Query\Expr\Base.php:88
#0 /path/to/project/vendor\doctrine\orm\lib\Doctrine\ORM\Query\Expr\Base.php(70): Doctrine\ORM\Query\Expr\Base->add(1)
#1 /path/to/project/vendor\doctrine\orm\lib\Doctrine\ORM\Query\Expr\Base.php(59): Doctrine\ORM\Query\Expr\Base->addMultiple(Array)
#2 /path/to/project/vendor\doctrine\orm\lib\Doctrine\ORM\QueryBuilder.php(774): Doctrine\ORM\Query\Expr\Base->__construct(Array)
#3 /path/to/project/tools\phpstan\vendor\phpstan\phpstan-doctrine\src\Type\Doctrine\QueryBuilder\QueryBuilderGetQueryDynamicReturnTypeExtension.php(121): Doctrine\ORM\QueryBuilder->select(1)
#4 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(3171): PHPStan\Type\Doctrine\QueryBuilder\QueryBuilderGetQueryDynamicReturnTypeExtension->getTypeFromMethodCall(Object(PHPStan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope))
#5 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1417): PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\Doctrine\QueryBuilder\SimpleQueryBuilderType), 'getQuery', Object(PhpParser\Node\Expr\MethodCall))
#6 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1423): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#7 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(440): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#8 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1417): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#9 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1423): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#10 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(440): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\MethodCall))
#11 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(1108): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#12 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(440): PHPStan\Analyser\MutatingScope->resolveType(Object(PhpParser\Node\Expr\Cast\Bool_))
#13 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionReturnTypeCheck.php(55): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\Cast\Bool_))
#14 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/ReturnTypeRule.php(43): PHPStan\Rules\FunctionReturnTypeCheck->checkReturnType(Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Type\BooleanType), Object(PhpParser\Node\Expr\Cast\Bool_), Object(PhpParser\Node\Stmt\Return_), 'Method T3\\UserB...', 'Method T3\\UserB...', 'Method T3\\UserB...', 'Method T3\\UserB...', false)
#15 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(69): PHPStan\Rules\Methods\ReturnTypeRule->processNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
#16 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.php(91): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
#17 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(404): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
#18 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(312): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope))
#19 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(254): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Return_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#20 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(419): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#21 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(254): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#22 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(503): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array, Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer))
#23 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(254): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#24 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(469): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#25 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(222): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#26 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(149): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#27 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(52): PHPStan\Analyser\FileAnalyser->analyseFile('/path/to/project/...', Array, Object(PHPStan\Rules\Registry), NULL)
#28 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(56): PHPStan\Analyser\Analyser->analyse(Array, Object(Closure), NULL, true, Array)
#29 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(148): PHPStan\Command\AnalyserRunner->runAnalyser(Array, Array, Object(Closure), NULL, true, true, '/path/to/project/...', NULL, NULL, Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput))
#30 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(79): PHPStan\Command\AnalyseApplication->runAnalyser(Array, Array, true, '/path/to/project/...', Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput))
#31 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(157): PHPStan\Command\AnalyseApplication->analyse(Array, false, Object(PHPStan\Command\Symfony\SymfonyOutput), Object(PHPStan\Command\Symfony\SymfonyOutput), false, true, '/path/to/project/...', Array, Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput))
#32 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(228): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Output\ConsoleOutput))
#33 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(856): _PHPStan_8f2e45ccf\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Output\ConsoleOutput))
#34 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(237): _PHPStan_8f2e45ccf\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Output\ConsoleOutput))
#35 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(138): _PHPStan_8f2e45ccf\Symfony\Component\Console\Application->doRun(Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_8f2e45ccf\Symfony\Component\Console\Output\ConsoleOutput))
#36 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(82): _PHPStan_8f2e45ccf\Symfony\Component\Console\Application->run()
#37 phar:///path/to/tools/phpstan/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(83): _PHPStan_8f2e45ccf\{closure}()
#38 /path/to/project/tools\phpstan\vendor\phpstan\phpstan\phpstan(8): require('phar:///path/to/...')
#39 {main}
~~~

phpstan: 0.12.94
phpstan-doctrine: 0.12.42

Kind regards
Matthias

**Comment by ondrejmirtes** [comment]
Can you please also show the analysed piece of code that PHPStan crashes on?
