### ISSUE TITLE
Internal exception since version 2.1.0: Incompatibility with doctrine/dbal 3.x

### ISSUE THREAD

**Issue by annervisser** [phpstan/phpstan-doctrine#256]
Since version 2.1.0 of this plugin phpstan is encountering an internal error:
`Internal error: assert($type instanceof ReflectionNamedType)`
```
Uncaught Error: Class "Doctrine\DBAL\Platforms\MySqlPlatform" not found in /home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan-doctrine/src/Doctrine/Mapping/ClassMetadataFactory.php:39
#0 /home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(461): PHPStan\Doctrine\Mapping\ClassMetadataFactory->initialize()
#1 /home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(77): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->isTransient()
#2 /home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan-doctrine/src/Rules/Doctrine/ORM/EntityNotFinalRule.php(41): PHPStan\Type\Doctrine\ObjectMetadataResolver->isTransient()
#3 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(94): PHPStan\Rules\Doctrine\ORM\EntityNotFinalRule->processNode()
#4 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(521): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
#5 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#6 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(510): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#7 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(269): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#8 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(181): PHPStan\Analyser\NodeScopeResolver->processNodes()
#9 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(69): PHPStan\Analyser\FileAnalyser->analyseFile()
#10 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse()
#11 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(163): PHPStan\Command\AnalyserRunner->runAnalyser()
#12 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(95): PHPStan\Command\AnalyseApplication->runAnalyser()
#13 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(175): PHPStan\Command\AnalyseApplication->analyse()
#14 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute()
#15 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(848): _PHPStan_70b6e53dc\Symfony\Component\Console\Command\Command->run()
#16 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->doRunCommand()
#17 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->doRun()
#18 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(94): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->run()
#19 phar:///home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(95): _PHPStan_70b6e53dc\{closure}()
#20 /home/anner/code/mezzio-test/php-ddd-onion-experimenting/vendor/phpstan/phpstan/phpstan(8): require('...')
#21 {main}

```

**Comment by ondrejmirtes** [comment]
Please test the new release 1.2.2: https://github.com/phpstan/phpstan-doctrine/releases/tag/1.2.2

Sorry for the inconvenience!
