### ISSUE TITLE
Doctrinemigrations desn't work after 1.2

### ISSUE THREAD

**Issue by mmarton** [phpstan/phpstan-doctrine#257]
After 1.2. I got the following error for most of my migration files

```
Internal error: Internal error: Class                                      
     "Doctrine\DBAL\Platforms\MySqlPlatform" not found in file                  
     /var/www/html/migrations/2021/12/Version20211213132741.php                 
     Run PHPStan with --debug option and post the stack trace to:               
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md       
```

and with --debug:
```
Uncaught Error: Class "Doctrine\DBAL\Platforms\MySqlPlatform" not found in .../vendor/phpstan/phpstan-doctrine/src/Doctrine/Mapping/ClassMetadataFactory.php:39
#0 .../vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(461): PHPStan\Doctrine\Mapping\ClassMetadataFactory->initialize()
#1 .../vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(77): Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->isTransient()
#2 .../vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(107): PHPStan\Type\Doctrine\ObjectMetadataResolver->isTransient()
#3 .../vendor/phpstan/phpstan-doctrine/src/Rules/Doctrine/ORM/PropertiesExtension.php(23): PHPStan\Type\Doctrine\ObjectMetadataResolver->getClassMetadata()
#4 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Rules/DeadCode/UnusedPrivatePropertyRule.php(103): PHPStan\Rules\Doctrine\ORM\PropertiesExtension->isAlwaysRead()
#5 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(94): PHPStan\Rules\DeadCode\UnusedPrivatePropertyRule->processNode()
#6 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(545): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}()
#7 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(298): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#8 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(510): PHPStan\Analyser\NodeScopeResolver->processStmtNodes()
#9 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(269): PHPStan\Analyser\NodeScopeResolver->processStmtNode()
#10 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(181): PHPStan\Analyser\NodeScopeResolver->processNodes()
#11 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Analyser/Analyser.php(69): PHPStan\Analyser\FileAnalyser->analyseFile()
#12 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyserRunner.php(62): PHPStan\Analyser\Analyser->analyse()
#13 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(163): PHPStan\Command\AnalyserRunner->runAnalyser()
#14 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseApplication.php(95): PHPStan\Command\AnalyseApplication->runAnalyser()
#15 phar://.../vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(175): PHPStan\Command\AnalyseApplication->analyse()
#16 phar://.../vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute()
#17 phar://.../vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(848): _PHPStan_70b6e53dc\Symfony\Component\Console\Command\Command->run()
#18 phar://.../vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(259): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->doRunCommand()
#19 phar://.../vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->doRun()
#20 phar://.../vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(94): _PHPStan_70b6e53dc\Symfony\Component\Console\Application->run()
#21 phar://.../vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(95): _PHPStan_70b6e53dc\{closure}()
#22 .../vendor/phpstan/phpstan/phpstan(8): require('...')
#23 .../vendor/bin/phpstan(107): include('...')
#24 {main}
```

**Comment by ondrejmirtes** [comment]
Please test the new release 1.2.2: https://github.com/phpstan/phpstan-doctrine/releases/tag/1.2.2

Sorry for the inconvenience!

**Comment by mmarton** [comment]
thanks for the quick fix
