### ISSUE TITLE
Internal error: assert($this->lexer->lookahead !== null)

### ISSUE THREAD

**Issue by eliashaeussler** [phpstan/phpstan-doctrine#406]
I get this exception when running PHPStan v1.9.4 with `phpstan/phpstan-doctrine` v1.3.27 installed:

```
Internal error: Internal error: assert($this->lexer->lookahead !== null) in file
/xxx/src/Repository/ServiceRepository.php
```

<details>
<summary>Stacktrace</summary>

```
#0 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2580): assert(false,
'assert($this->l...')
#1 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2534):
Doctrine\ORM\Query\Parser->SimpleConditionalExpression()
#2 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2513):
Doctrine\ORM\Query\Parser->ConditionalPrimary()
#3 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2481):
Doctrine\ORM\Query\Parser->ConditionalFactor()
#4 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(2456):
Doctrine\ORM\Query\Parser->ConditionalTerm()
#5 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1391):
Doctrine\ORM\Query\Parser->ConditionalExpression()
#6 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(882):
Doctrine\ORM\Query\Parser->WhereClause()
#7 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(849):
Doctrine\ORM\Query\Parser->SelectStatement()
#8 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(256):
Doctrine\ORM\Query\Parser->QueryLanguage()
#9 /xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(356):
Doctrine\ORM\Query\Parser->getAST()
#10
/xxx/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/Query/QueryResultTypeWalker
.php(119): Doctrine\ORM\Query\Parser->parse()
#11
/xxx/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/QueryBuilder/QueryBuilderGe
tQueryDynamicReturnTypeExtension.php(163):
PHPStan\Type\Doctrine\Query\QueryResultTypeWalker::walk(Object(Doctrine\ORM\Query),
Object(PHPStan\Type\Doctrine\Query\QueryResultTypeBuilder), Object(PHPStan\Type\Doctrine\DescriptorRegistry))
#12
/xxx/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/QueryBuilder/QueryBuilderGe
tQueryDynamicReturnTypeExtension.php(146):
PHPStan\Type\Doctrine\QueryBuilder\QueryBuilderGetQueryDynamicReturnTypeExtension->getQueryType('SELECT s FROM
A...')
#13
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(338
8):
PHPStan\Type\Doctrine\QueryBuilder\QueryBuilderGetQueryDynamicReturnTypeExtension->getTypeFromMethodCall(Object(PHP
Stan\Reflection\ResolvedMethodReflection), Object(PhpParser\Node\Expr\MethodCall),
Object(PHPStan\Analyser\MutatingScope))
#14
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(140
2):
PHPStan\Analyser\MutatingScope->methodCallReturnType(Object(PHPStan\Type\Doctrine\QueryBuilder\BranchingQueryBuilde
rType), 'getQuery', Object(PhpParser\Node\Expr\MethodCall))
#15
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(140
8): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#16
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(558
): PHPStan\Analyser\MutatingScope->resolveType('$queryBuilder->...', Object(PhpParser\Node\Expr\MethodCall))
#17
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(140
2): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#18
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(140
8): PHPStan\Analyser\MutatingScope->PHPStan\Analyser\{closure}()
#19
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(558
): PHPStan\Analyser\MutatingScope->resolveType('$queryBuilder->...', Object(PhpParser\Node\Expr\MethodCall))
#20
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Rules/FunctionReturnTypeCheck.
php(57): PHPStan\Analyser\MutatingScope->getType(Object(PhpParser\Node\Expr\MethodCall))
#21
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Methods/ReturnTypeRule.p
hp(43): PHPStan\Rules\FunctionReturnTypeCheck->checkReturnType(Object(PHPStan\Analyser\MutatingScope),
Object(PHPStan\Type\ArrayType), Object(PhpParser\Node\Expr\MethodCall), Object(PhpParser\Node\Stmt\Return_),
'Method App\\Repo...', 'Method App\\Repo...', 'Method App\\Repo...', 'Method App\\Repo...', false)
#22
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106)
: PHPStan\Rules\Methods\ReturnTypeRule->processNode(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope))
#23
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassStatementsGatherer.p
hp(98): PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope))
#24
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(506): PHPStan\Node\ClassStatementsGatherer->__invoke(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope))
#25
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(415): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope))
#26
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(360): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Return_),
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#27
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(521): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array,
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#28
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(360): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),
Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),
Object(PHPStan\Analyser\StatementContext))
#29
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(599): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array,
Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer),
Object(PHPStan\Analyser\StatementContext))
#30
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(360): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_),
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#31
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(571): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array,
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#32
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php
(327): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_),
Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))
#33
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175)
: PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))
#34
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(147)
: PHPStan\Analyser\FileAnalyser->analyseFile('/xxx...', Array, Object(PHPStan\Rules\LazyRegistry),
Object(PHPStan\Collectors\Registry), NULL)
#35
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Eve
nement/EventEmitterTrait.php(97): PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)
#36
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decod
er.php(110): _PHPStan_5c71ab23c\Evenement\EventEmitter->emit('data', Array)
#37
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Eve
nement/EventEmitterTrait.php(97): _PHPStan_5c71ab23c\Clue\React\NDJson\Decoder->handleData(Array)
#38
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(6
2): _PHPStan_5c71ab23c\Evenement\EventEmitter->emit('data', Array)
#39
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Eve
nement/EventEmitterTrait.php(97):
_PHPStan_5c71ab23c\React\Stream\Util::_PHPStan_5c71ab23c\React\Stream\{closure}('{"action":"anal...')
#40
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexReso
urceStream.php(154): _PHPStan_5c71ab23c\Evenement\EventEmitter->emit('data', Array)
#41
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/Stream
SelectLoop.php(201): _PHPStan_5c71ab23c\React\Stream\DuplexResourceStream->handleData(Resource id #3570)
#42
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/Stream
SelectLoop.php(173): _PHPStan_5c71ab23c\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#43
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(107)
: _PHPStan_5c71ab23c\React\EventLoop\StreamSelectLoop->run()
#44
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Com
mand.php(259):
PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_5c71ab23c\Symfony\Component\Console\Input\ArgvInput),
Object(_PHPStan_5c71ab23c\Symfony\Component\Console\Output\ConsoleOutput))
#45
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application
.php(868):
_PHPStan_5c71ab23c\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_5c71ab23c\Symfony\Component\Conso
le\Input\ArgvInput), Object(_PHPStan_5c71ab23c\Symfony\Component\Console\Output\ConsoleOutput))
#46
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application
.php(259):
_PHPStan_5c71ab23c\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand),
Object(_PHPStan_5c71ab23c\Symfony\Component\Console\Input\ArgvInput),
Object(_PHPStan_5c71ab23c\Symfony\Component\Console\Output\ConsoleOutput))
#47
phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application
.php(157):
_PHPStan_5c71ab23c\Symfony\Component\Console\Application->doRun(Object(_PHPStan_5c71ab23c\Symfony\Component\Console
\Input\ArgvInput), Object(_PHPStan_5c71ab23c\Symfony\Component\Console\Output\ConsoleOutput))
#48 phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124):
_PHPStan_5c71ab23c\Symfony\Component\Console\Application->run()
#49 phar:///xxx/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125):
_PHPStan_5c71ab23c\{closure}()
#50 /xxx/vendor/phpstan/phpstan/phpstan(8): require('phar:///xxx...')
#51 /xxx/vendor/bin/phpstan(120): include('/xxx...')
#52 {main}
Child process error (exit code 1):
```

</details>

<details>
<summary>Affected code</summary>

```php
<?php

declare(strict_types=1);

namespace App\Repository;

use App\Entity\Service;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * @method Service|null find($id, $lockMode = null, $lockVersion = null)
 * @method Service|null findOneBy(array $criteria, array $orderBy = null)
 * @method Service[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 *
 * @extends ServiceEntityRepository<Service>
 */
final class ServiceRepository extends ServiceEntityRepository
{
    public function __construct(
        ManagerRegistry $registry,
    ) {
        parent::__construct($registry, Service::class);
    }

    /**
     * @return Service[]
     */
    public function findAll(bool $includeDisabled = false): array
    {
        if (!$includeDisabled) {
            return $this->findBy(['disabled' => false]);
        }

        return $this->findBy([]);
    }

    /**
     * @param int[] $ids
     *
     * @return Service[] Returns an array of Service objects
     */
    public function findByIds(array $ids, bool $includeDisabled = false): array
    {
        $queryBuilder = $this->createQueryBuilder('s');
        $constraint = $queryBuilder->expr()->andX();
        $constraint->add($queryBuilder->expr()->in('s.id', $ids));

        if (!$includeDisabled) {
            $constraint->add($queryBuilder->expr()->eq('s.disabled', 0));
        }

        return $queryBuilder
            ->where($constraint)
            ->getQuery()
            ->getResult();
    }

    public function countAll(): int
    {
        $queryBuilder = $this->createQueryBuilder('s');

        return (int) $queryBuilder
            ->select($queryBuilder->expr()->count('s.id'))
            ->getQuery()
            ->getSingleScalarResult();
    }
}
```

</details>

I was able to track this down with something introduced in `phpstan/phpstan-doctrine` v1.2.1 since it works with v1.2.0.

---

Installed Doctrine packages:

```
doctrine/annotations                    1.14.2
doctrine/cache                          2.2.0
doctrine/collections                    2.1.1
doctrine/common                         3.4.3
doctrine/data-fixtures                  1.6.1
doctrine/dbal                           3.5.2
doctrine/deprecations                   v1.0.0
doctrine/doctrine-bundle                2.7.2
doctrine/doctrine-fixtures-bundle       3.4.2
doctrine/doctrine-migrations-bundle     3.2.2
doctrine/event-manager                  1.2.0
doctrine/inflector                      2.0.6
doctrine/instantiator                   1.4.1
doctrine/lexer                          1.2.3
doctrine/migrations                     3.5.2
doctrine/orm                            2.14.0
doctrine/persistence                    3.1.2
doctrine/sql-formatter                  1.1.3
phpstan/phpstan-doctrine                1.3.27
symfony/doctrine-bridge                 v6.2.2
```

Installed PHPStan packages:

```
phpstan/phpstan                         1.9.4
phpstan/phpstan-doctrine                1.3.27
phpstan/phpstan-symfony                 1.2.19
```

**Comment by ondrejmirtes** [comment]
This is a bug in doctrine/orm and internal state of the DQL parser. phpstan-doctrine's test suite fails the same way when running on a machine with enabled `assert()` calls.

We need to reproduce this problem as a unit test for doctrine/orm.

**Comment by Fahl-Design** [comment]
The quick fix for me was/is: downgrade `doctrine/orm` to `2.13.*`

**Comment by ondrejmirtes** [comment]
Should be silenced now.
