### ISSUE TITLE
Internal error: [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_CURLY_BRACES, got '('

### ISSUE THREAD

**Issue by gremo** [phpstan/phpstan-doctrine#426]
Seems that `indexes` cause some problem (running `phpstan --debug` to avoid caching):

> Internal error: Internal error: [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_CURLY_BRACES, got '(' at position 50 in  
     class App\Entity\ProductVariant. in file /workspaces/myproject/src/Entity/ProductVariant.php                                          
     Run PHPStan with -v option and post the stack trace to:                                                                                        
     https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md                                                                           
     Child process error (exit code 1):     

Minimal file to reproduce:

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table("iostarticoli_var", indexes={@ORM\Index(columns={"FL_ATTIVO"})})
 */
class ProductVariant
{
    /**
     * @ORM\Column("FL_ATTIVO", type="boolean")
     */
    public ?bool $enabled;
}
```

**PHPStan - PHP Static Analysis Tool 1.9.17**

```bash
composer show phpstan/phpstan-doctrine
name     : phpstan/phpstan-doctrine
descrip. : Doctrine extensions for PHPStan
keywords : 
versions : * 1.3.32
```

**Comment by ondrejmirtes** [comment]
The full stack trace which the error message instructs you to paste, would be useful 😊

**Comment by gremo** [comment]
@ondrejmirtes here we are, thanks! Hope that is my bad.... or get fixed:

```txt
 -- ----------------------------------------------------------------------------------------------------------------------------------------------- 
     Error                                                                                                                                          
 -- ----------------------------------------------------------------------------------------------------------------------------------------------- 
     Internal error: Internal error: [Syntax Error] Expected Doctrine\Common\Annotations\DocLexer::T_CLOSE_CURLY_BRACES, got '(' at position 50 in  
     class App\Entity\ProductVariant. in file /workspaces/myproject/src/Entity/ProductVariant.php                                          
                                                                                                                                                    
     Post the following stack trace to https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md:                                        
     #0 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(464):                              
     Doctrine\Common\Annotations\AnnotationException::syntaxError('Expected Doctri...')                                                             
     #1 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(416):                              
     Doctrine\Common\Annotations\DocParser->syntaxError('Doctrine\\Common...')                                                                      
     #2 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1339):                             
     Doctrine\Common\Annotations\DocParser->match(102)                                                                                              
     #3 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1237):                             
     Doctrine\Common\Annotations\DocParser->Arrayx()                                                                                                
     #4 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1300):                             
     Doctrine\Common\Annotations\DocParser->PlainValue()                                                                                            
     #5 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1220):                             
     Doctrine\Common\Annotations\DocParser->FieldAssignment()                                                                                       
     #6 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1063):                             
     Doctrine\Common\Annotations\DocParser->Value()                                                                                                 
     #7 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(1035):                             
     Doctrine\Common\Annotations\DocParser->Values()                                                                                                
     #8 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(869):                              
     Doctrine\Common\Annotations\DocParser->MethodCall()                                                                                            
     #9 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(719):                              
     Doctrine\Common\Annotations\DocParser->Annotation()                                                                                            
     #10 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(376):                             
     Doctrine\Common\Annotations\DocParser->Annotations()                                                                                           
     #11 /workspaces/myproject/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(146):                      
     Doctrine\Common\Annotations\DocParser->parse('/**\n * @ORM\\Tab...', 'class App\\Entit...')                                                    
     #12 /workspaces/myproject/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/Driver/AnnotationDriver.php(179):              
     Doctrine\Common\Annotations\AnnotationReader->getClassAnnotations(Object(ReflectionClass))                                                     
     #13 /workspaces/myproject/vendor/doctrine/persistence/lib/Doctrine/Persistence/Mapping/AbstractClassMetadataFactory.php(462):         
     Doctrine\Persistence\Mapping\Driver\AnnotationDriver->isTransient('App\\Entity\\Prod...')                                                      
     #14 /workspaces/myproject/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(82):                           
     Doctrine\Persistence\Mapping\AbstractClassMetadataFactory->isTransient('App\\Entity\\Prod...')                                                 
     #15 /workspaces/myproject/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/ObjectMetadataResolver.php(117):                          
     PHPStan\Type\Doctrine\ObjectMetadataResolver->isTransient('App\\Entity\\Prod...')                                                              
     #16 /workspaces/myproject/vendor/phpstan/phpstan-doctrine/src/Rules/Doctrine/ORM/PropertiesExtension.php(70):                         
     PHPStan\Type\Doctrine\ObjectMetadataResolver->getClassMetadata('App\\Entity\\Prod...')                                                         
     #17 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Node/ClassPropertiesNode.php(130):                           
     PHPStan\Rules\Doctrine\ORM\PropertiesExtension->isInitialized(Object(PHPStan\Reflection\Php\PhpPropertyReflection), 'enabled')                 
     #18 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Rules/Properties/MissingReadOnlyPropertyAssignRule.php(37):  
     PHPStan\Node\ClassPropertiesNode->getUninitializedProperties(Object(PHPStan\Analyser\MutatingScope), Array)                                    
     #19 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(106):                              
     PHPStan\Rules\Properties\MissingReadOnlyPropertyAssignRule->processNode(Object(PHPStan\Node\ClassPropertiesNode),                              
     Object(PHPStan\Analyser\MutatingScope))                                                                                                        
     #20 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(600):                         
     PHPStan\Analyser\FileAnalyser->PHPStan\Analyser\{closure}(Object(PHPStan\Node\ClassPropertiesNode), Object(PHPStan\Analyser\MutatingScope))    
     #21 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(360):                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_), Object(PHPStan\Analyser\MutatingScope),                
     Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                    
     #22 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(571):                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array, Object(PHPStan\Analyser\MutatingScope),    
     Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                    
     #23 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(327):                         
     PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_), Object(PHPStan\Analyser\MutatingScope),            
     Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                    
     #24 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(175):                              
     PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))                               
     #25 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(148):                              
     PHPStan\Analyser\FileAnalyser->analyseFile('/workspaces/xbi...', Array, Object(PHPStan\Rules\LazyRegistry),                                    
     Object(PHPStan\Collectors\Registry), NULL)                                                                                                     
     #26                                                                                                                                            
     phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):  
     PHPStan\Command\WorkerCommand->PHPStan\Command\{closure}(Array)                                                                                
     #27 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(110):                   
     _PHPStan_d3e3292d7\Evenement\EventEmitter->emit('data', Array)                                                                                 
     #28                                                                                                                                            
     phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):  
     _PHPStan_d3e3292d7\Clue\React\NDJson\Decoder->handleData(Array)                                                                                
     #29 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62):                            
     _PHPStan_d3e3292d7\Evenement\EventEmitter->emit('data', Array)                                                                                 
     #30                                                                                                                                            
     phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(97):  
     _PHPStan_d3e3292d7\React\Stream\Util::_PHPStan_d3e3292d7\React\Stream\{closure}('{"action":"anal...')                                          
     #31 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(154):           
     _PHPStan_d3e3292d7\Evenement\EventEmitter->emit('data', Array)                                                                                 
     #32 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201):           
     _PHPStan_d3e3292d7\React\Stream\DuplexResourceStream->handleData(Resource id #3867)                                                            
     #33 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173):           
     _PHPStan_d3e3292d7\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                                                               
     #34 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(108):                              
     _PHPStan_d3e3292d7\React\EventLoop\StreamSelectLoop->run()                                                                                     
     #35 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259):                 
     PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_d3e3292d7\Symfony\Component\Console\Input\ArgvInput),                                   
     Object(_PHPStan_d3e3292d7\Symfony\Component\Console\Output\ConsoleOutput))                                                                     
     #36 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870):                     
     _PHPStan_d3e3292d7\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_d3e3292d7\Symfony\Component\Console\Input\ArgvInput),        
     Object(_PHPStan_d3e3292d7\Symfony\Component\Console\Output\ConsoleOutput))                                                                     
     #37 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261):                     
     _PHPStan_d3e3292d7\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand),                                  
     Object(_PHPStan_d3e3292d7\Symfony\Component\Console\Input\ArgvInput),                                                                          
     Object(_PHPStan_d3e3292d7\Symfony\Component\Console\Output\ConsoleOutput))                                                                     
     #38 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):                     
     _PHPStan_d3e3292d7\Symfony\Component\Console\Application->doRun(Object(_PHPStan_d3e3292d7\Symfony\Component\Console\Input\ArgvInput),          
     Object(_PHPStan_d3e3292d7\Symfony\Component\Console\Output\ConsoleOutput))                                                                     
     #39 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(124):                                                
     _PHPStan_d3e3292d7\Symfony\Component\Console\Application->run()                                                                                
     #40 phar:///workspaces/myproject/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(125): _PHPStan_d3e3292d7\{closure}()                 
     #41 /workspaces/myproject/vendor/phpstan/phpstan/phpstan(7): require('phar:///workspa...')                                            
     #42 /workspaces/myproject/vendor/bin/phpstan(115): include('/workspaces/xbi...')                                                      
     #43 {main}                                                                                                                                     
     Child process error (exit code 1):    
```

**Comment by gremo** [comment]
@ondrejmirtes any update? Do you need more context or info? Thank you

**Comment by ondrejmirtes** [comment]
What's your expectation? The problem is that this parse error is thrown by Doctrine itself, which means that Doctrine doesn't like your annotation.

Do you expect PHPStan not to crash (but print an error about a syntax error), or do you expect this parse error to not happen at all?

**Comment by gremo** [comment]
I've somehow updated vendors and/or phpstan, now works without Doctrine annotations errors. Thanks @ondrejmirtes
