### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by yura3d** [phpstan/phpstan-doctrine#73]
```
 ------ --------------------------------------------------------------
  Line   Doctrine/Expr/PartialSelect.php
 ------ --------------------------------------------------------------
         Internal error: Class 'parent' not found
         Run PHPStan with --debug option and post the stack trace to:
         https://github.com/phpstan/phpstan/issues/new
 ------ --------------------------------------------------------------
```

```
PHP Fatal error:  Uncaught Error: Class 'parent' not found in /.../vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/QueryBuilder/Expr/NewExprDynamicReturnTypeExtension.php:52
Stack trace:
#0 /.../vendor/phpstan/phpstan/src/Analyser/Scope.php(1498): PHPStan\Type\Doctrine\QueryBuilder\Expr\NewExprDynamicReturnTypeExtension->getTypeFromStaticMethodCall(Object(PHPStan\Reflection\Php\PhpMethodReflection), Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\Scope))
#1 /.../vendor/phpstan/phpstan/src/Analyser/Scope.php(372): PHPStan\Analyser\Scope->resolveType(Object(PhpParser\Node\Expr\StaticCall))
#2 /.../vendor/phpstan/phpstan/src/Rules/FunctionCallParametersCheck.php(98): PHPStan\Analyser\Scope->getType(Object(PhpParser\Node\Expr\StaticCall))
#3 /.../vendor/phpstan/phpstan/src/Rules/Methods/CallStaticMethodsRule.php(265): PHPStan\Rules\FunctionCallParamet in /.../vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/QueryBuilder/Expr/NewExprDynamicReturnTypeExtension.php on line 52
```

**Comment by ondrejmirtes** [comment]
Fixed, thanks: https://github.com/phpstan/phpstan-doctrine/commit/e5c4bcbe90ec1eb149552b00e7fb0632a54a5a54

Will release promptly.

**Comment by yura3d** [comment]
@ondrejmirtes I've detected strange behavior after applying this commit:

![image](https://user-images.githubusercontent.com/10958696/66417637-205bc080-ea09-11e9-9992-9c767a87cac6.png)

`$aoSelect` is object, but phpstan sees it as void.

And I found what causes this problem. If I pass simple arg (array, for example) to any `Expr` object constructor:
```
$this->qb->add('select', new \Doctrine\ORM\Query\Expr\Andx(['test']));
```
Everything is fine. But if I pass the result of the function (`array_merge`, for example, which always returns array):
```
$this->qb->add('select', new \Doctrine\ORM\Query\Expr\Andx(array_merge(['test'])));
```
phpstan shows:
```
Parameter #2 $dqlPart of method Doctrine\ORM\QueryBuilder::add() expects array|object, void given.
```

Also I see strange situation if I pass simple array with numeric elements to any `Expr` object constructor:
```
$this->qb->add('select', new \Doctrine\ORM\Query\Expr\Andx([0, 1000]));
```
phpstan shows:
```
Internal error: Expression of type '' not allowed in this context.
Run PHPStan with --debug option and post the stack trace to:
https://github.com/phpstan/phpstan/issues/new
```
Stack trace is:
```
#0 /home/***/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Expr/Base.php(74): Doctrine\ORM\Query\Expr\Base->add(0)
#1 /home/***/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Expr/Base.php(63): Doctrine\ORM\Query\Expr\Base->addMultiple(Array)
#2 /home/***/vendor/phpstan/phpstan-doctrine/src/Type/Doctrine/QueryBuilder/Expr/NewExprDynamicReturnTypeExtension.php(71): Doctrine\ORM\Query\Expr\Base->__construct(Array)
#3 /home/***/vendor/phpstan/phpstan/src/Analyser/Scope.php(1089): PHPStan\Type\Doctrine\QueryBuilder\Expr\NewExprDynamicReturnTypeExtension->getTypeFromStaticMethodCall(Object(PHPStan\Reflection\Php\PhpMethodReflection), Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\Scope))
#4 /home/v in /home/***/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Expr/Base.php on line 95
```
