### ISSUE TITLE
Uncaught PHPStan\ShouldNotHappenException RepositoryMethodCallRule.php

### ISSUE THREAD

**Issue by Erathian** [phpstan/phpstan-doctrine#89]
Hi,

I got an issue (stack trace at the end):

Uncaught PHPStan\ShouldNotHappenException: Please provide the "objectManagerLoader" setting for magic repository Doctrine\ORM\EntityRepository::findOneBy() RepositoryMethodCallRule.php:68

This happens when I have following property and findOneByNumber method using findOneBy method of EntityRepository. The EntityRepository is subclass of Doctrine\ORM\EntityRepository.

```php
/** @var \Kdyby\Doctrine\EntityRepository|\Doctrine\ORM\EntityRepository<Invoice> */
private $repository;

/**
* OrderRepository constructor.
* @param \Kdyby\Doctrine\EntityManager $em
 */
public function __construct(\Kdyby\Doctrine\EntityManager $em)
{
	$this->em = $em;
	$this->repository = $em->getRepository(Invoice::class);
}

/**
	 * @param int $number
	 *
	 * @return null|Invoice
	 */
	public function findOneByNumber($number)
	{
		return $this->repository->findOneBy(['number' => $number]);
	}
```

```
Stack trace:
#0 C:\Web\Apps\zvz-new\home\libs\vendor\phpstan\phpstan\src\Analyser\Analyser.php(154): PHPStan\Rules\Doctrine\ORM\RepositoryMethodCallRule->processNode(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\Scope))
#1 C:\Web\Apps\zvz-new\home\libs\vendor\phpstan\phpstan\src\Analyser\NodeScopeResolver.php(1698): PHPStan\Analyser\Analyser->PHPStan\Analyser\{closure}(Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\Scope))
#2 C:\Web\Apps\zvz-new\home\libs\vendor\phpstan\phpstan\src\Analyser\NodeScopeResolver.php(1146): PHPStan\Analyser\NodeScopeResolver->callNodeCallbackWithExpression(Object(Closure), Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\Scope), Object(PHPSta in C:\Web\Apps\zvz-new\home\libs\vendor\phpstan\phpstan-doctrine\src\Rules\Doctrine\ORM\RepositoryMethodCallRule.php on line 68
```

I can provide more info if needed.

Thanks!

**Comment by ondrejmirtes** [comment]
Please try the latest version.
